import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="bg-amber-300 w-full h-[60px]">
            <h1 className="p-4.5 font-extrabold">skill mentorx</h1>
          </div>
        </header>
        {children}

        <footer>
          <div className="bg-black w-full h-50 flex align-bottom">

          </div>
        </footer>
      </body>
    </html>
  );
}
